# The site is already built into the "site" folder. Netlify just publishes it.
[build]
  publish = "site"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
